sudo: required
services:
  - docker
before install:
  - docker build -t dvontrec/colors-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dvontrec/colors-client-test npm run test:coverage

after_sucess:
  - docker build -t dvontrec/colors-client ./client
  - docker build -t dvontrec/colors-server ./server
  - docker build -t dvontrec/colors-api ./api
