sudo: required
services:
  - docker
before install:
  - docker build -t dvontrec/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dvontrec/client-test npm run test:coverage
after_sucess:
  - docker build -t dvontrec/colors-client ./client
  - docker build -t dvontrec/colors-server ./server
  - docker build -t dvontrec/colors-api ./api
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dvontrec/colors-client
  - docker push dvontrec/colors-server
  - docker push dvontrec/colors-api
