sudo: required
services:
  - docker
before_install:
  - docker build -t dvontrec/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dvontrec/client-test npm run test:coverage
after_success:
  - docker build -t dvontrec/colors-client ./client
  - docker build -t dvontrec/colors-nginx ./nginx
  - docker build -t dvontrec/colors-api ./api
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dvontrec/colors-client
  - docker push dvontrec/colors-nginx
  - docker push dvontrec/colors-api
deploy:
  provider: 'elasticbeanstalk'
  region: 'us-east-1'
  app: Color-Creator
  env: ColorCreator-env
  bucket_name: elasticbeanstalk-us-east-1-092753704309
  bucket_path: Color-Creator
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
