version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8081:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    # Tells docker to start sql first
    depends_on:
      - 'sql'
    restart: always
    ports:
      - '8083:8001'
    volumes:
      - ./api:/app
    environment:
      DBUSER: root
      DBPASSWORD: password
      DBHOST: sql
      DBNAME: colors
      DBPORT: '3306'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  sql:
    build:
      dockerfile: Dockerfile.dev
      context: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: colors
    expose:
      - '3306'
    ports:
      - '3306:3306'
