# Derived from official mysql image (our base image)
FROM mysql

# Add a database
ENV MYSQL_DATABASE colors
ENV MYSQL_ROOT_PASSWORD supersecret

# All scripts in docker-entrypoint-initdb.d/ are automatically executed during container startup
COPY . /docker-entrypoint-initdb.d/